services:
  - type: web
    name: bot-taixiu-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true

services:
  - type: web
    name: taixiu-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    region: singapore
    plan: free
